# Generated by Django 5.2.7 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaign_assigned_doctors"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("doctors_only", "Doctors & Admin Only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
